 

import java.util.Scanner;
class MyThrow extends Exception{
   MyThrow(String s){
    super(s);
    System.out.println(s);
  }
  public String getMessage(){
    return "This is the method in the custom expection";
  }
}

public class Main {
    public static void main(String[] args) {
      //----------------------------
        // Problem 1
      //---------------------
       Scanner Sc = new Scanner(System.in);
       System.out.println(" Oestion1:  Write a java program to demonstrate syntax, logical 2 runtime errors");
      System.out.println();
        // Syntax Error - int a = 7
        int age = 78;
        int year_born = 2000-78; // Logical error
//        System.out.println(6/0);

         
      //----------------------------
        // Problem 2
      //---------------------
       System.out.println("Qestion2:Write a java program that prints HaHa during Arithmetic exception and HeHe during an Illegal argument exception.");
      System.out.println();
        try{
            
            int a = 666/0;
        }
        catch (IllegalArgumentException e){
            System.out.println("HeHe");
        }
        catch (ArithmeticException e){
            System.out.println("Haha");
        }

        // Problem 3
      //----------------------------
        // Problem 3
      //---------------------
       System.out.println(" Oestion3 & 4 & 5:  Write a program that allows you to given. If max retries exceed 5 print errors and to throw a custom Exception if max retries are reached. ");
      System.out.println(" Q5 -- Wrap the program in Q3 inside a method which throws your custom Exception.");
        boolean flag = true;
        int [] marks = new int[5];
        marks[0] = 7;
        marks[1] = 56;
        marks[2] = 6;
      marks[3] = 29;
      marks[4] = 60;
        
        int index;
        int i = 0;
        while(flag && i<5){
            try {
                System.out.println("Enter the value of index between 0 and" +marks.length);
                index = Sc.nextInt();
                System.out.println("The value of marks[index] is " + marks[index]);
             
                break;
            }
            catch (Exception e) {
                System.out.println("Invalid Index");
                i++;
            }
           
        }
        if(i>=5){
            
          try{
             throw new MyThrow("Max retrieve more than available");
            
          }catch(MyThrow e){
            System.out.println("Error");
            System.out.println(e.getMessage());
          }
           
        }


    }
}
//  Write a java program to demonstrate syntax, logical 2 runtime errors.

// 2) Write a java program that prints HaHa during Arithmetic exception and HeHe during an Illegal argument exception.

// 3) Write a program that allows you to given. If max retries exceed 5 print "errors".

// 4) Modify program in Q3 to throw a custom Exception if max retries are reached. 

// 5) Wrap the program in Q3 inside a method which throws your custom Exception.
